### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#4]
Il semble bien, après un "pull" que le gabctk pose toujours problème. Voici le log : 

> Traceback (most recent call last):
  File "/opt/musite/deps/ext/gabc.py", line 265, in midi
    return self.gabc(fmt='midi', chemin=chemin, indice=indice)
  File "/opt/musite/deps/ext/gabc.py", line 243, in gabc
    raise ErreurCompilation('', '')
ext.txt.ErreurCompilation: ('', '')
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 932, in poser_note_precedente
    self.precedent.poser(pose)
AttributeError: 'NoneType' object has no attribute 'poser'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 428, in partition
    if len(partition) else None
  File "/opt/musite/deps/gabctk.py", line 575, in __init__
    else None
  File "/opt/musite/deps/gabctk.py", line 613, in __init__
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 732, in __init__
    self.traiter_gabc(gabc)
  File "/opt/musite/deps/gabctk.py", line 800, in traiter_gabc
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 916, in __init__
    self.poser_note_precedente()
  File "/opt/musite/deps/gabctk.py", line 934, in poser_note_precedente
    self.neume.syllabe.mot.precedent[-1].neume[-1].poser(pose)
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 932, in poser_note_precedente
    self.precedent.poser(pose)
AttributeError: 'NoneType' object has no attribute 'poser'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/ext/gabc.py", line 240, in gabc
    self.preparer_gabc(fmt, fichier)
  File "/opt/musite/deps/ext/gabc.py", line 315, in preparer_gabc
    transposition=self.proprietes[fmt]['transposition']
  File "/opt/musite/deps/ext/gabc.py", line 216, in partition
    else None
  File "/opt/musite/deps/gabctk.py", line 435, in partition
    if len(partition) else None
  File "/opt/musite/deps/gabctk.py", line 575, in __init__
    else None
  File "/opt/musite/deps/gabctk.py", line 613, in __init__
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 732, in __init__
    self.traiter_gabc(gabc)
  File "/opt/musite/deps/gabctk.py", line 800, in traiter_gabc
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 916, in __init__
    self.poser_note_precedente()
  File "/opt/musite/deps/gabctk.py", line 934, in poser_note_precedente
    self.neume.syllabe.mot.precedent[-1].neume[-1].poser(pose)
IndexError: list index out of range
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 932, in poser_note_precedente
    self.precedent.poser(pose)
AttributeError: 'NoneType' object has no attribute 'poser'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 428, in partition
    if len(partition) else None
  File "/opt/musite/deps/gabctk.py", line 575, in __init__
    else None
  File "/opt/musite/deps/gabctk.py", line 613, in __init__
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 732, in __init__
    self.traiter_gabc(gabc)
  File "/opt/musite/deps/gabctk.py", line 800, in traiter_gabc
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 916, in __init__
    self.poser_note_precedente()
  File "/opt/musite/deps/gabctk.py", line 934, in poser_note_precedente
    self.neume.syllabe.mot.precedent[-1].neume[-1].poser(pose)
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/gabctk.py", line 932, in poser_note_precedente
    self.precedent.poser(pose)
AttributeError: 'NoneType' object has no attribute 'poser'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/ext/gabc.py", line 240, in gabc
    self.preparer_gabc(fmt, fichier)
  File "/opt/musite/deps/ext/gabc.py", line 315, in preparer_gabc
    transposition=self.proprietes[fmt]['transposition']
  File "/opt/musite/deps/ext/gabc.py", line 216, in partition
    else None
  File "/opt/musite/deps/gabctk.py", line 435, in partition
    if len(partition) else None
  File "/opt/musite/deps/gabctk.py", line 575, in __init__
    else None
  File "/opt/musite/deps/gabctk.py", line 613, in __init__
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 732, in __init__
    self.traiter_gabc(gabc)
  File "/opt/musite/deps/gabctk.py", line 800, in traiter_gabc
    alterations=alterations
  File "/opt/musite/deps/gabctk.py", line 916, in __init__
    self.poser_note_precedente()
  File "/opt/musite/deps/gabctk.py", line 934, in poser_note_precedente
    self.neume.syllabe.mot.precedent[-1].neume[-1].poser(pose)
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/musite/deps/ext/gabc.py", line 265, in midi
    return self.gabc(fmt='midi', chemin=chemin, indice=indice)
  File "/opt/musite/deps/ext/gabc.py", line 243, in gabc
    raise ErreurCompilation('', '')
ext.txt.ErreurCompilation: ('', '')
Traceback (most recent call last):
  File "/opt/musite/deps/bottle.py", line 937, in _handle
    return route.call(**args)
  File "/opt/musite/deps/bottle.py", line 1878, in wrapper
    rv = callback(*a, **ka)
  File "/opt/musite/deps/i18n.py", line 463, in wrapper
    return callback(*args, **kwargs)
  File "/opt/musite/serveur.py", line 70, in afficher
    contenu = fonction(*arguments, **parametres)
  File "/opt/musite/serveur.py", line 833, in document_exporter
    rq.query.fmt, rq.forms.decode()
  File "/opt/musite/deps/controleur.py", line 410, in exporter
    + '?action=telecharger'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by jperon** [comment]
Pourriez-vous s'il vous plaît vérifier si cela est corrigé dans la dernière version ?

**Comment by mimo38** [comment]
NON...

**Comment by jperon** [comment]
Pourriez-vous m'envoyer le fichier sur lequel vous avez le problème, s'il vous plaît ?

**Comment by mimo38** [comment]
par exemple [là](https://github.com/jperon/graduale/blob/master/gabc/Sequence/VeniSancteSpiritus.gabc)
(présence du caractère ǽ à la ligne 4)

**Comment by jperon** [comment]
[Cette fois, c'est la bonne](https://musite.dtdns.net/fr/Graduale/gabc/Sequence/VeniSancteSpiritus.gabc). Pouvez-vous me confirmer que cela fonctionne aussi chez vous ?

**Comment by mimo38** [comment]
Non, cela ne fonctionne pas, et pas de production de log !
Par ailleurs, vous pouvez jeter un œil sur l'[Ave Verum](https://musite.dtdns.net/fr/Graduale/gabc/Sequence/AveVerum.gabc). Le point d'exclamation semble aussi poser problème, mais à GregorioTex cette fois.

**Comment by mimo38** [comment]
J'ai bien sûr exécuté un pull avant tout !

**Comment by jperon** [comment]
[Et pourtant](https://musite.dtdns.net/fr/Graduale/gabc/Sequence/VeniSancteSpiritus.gabc), ici ça fonctionne (de même que chez moi en local). Après avoir fait un pull, avez-vous relancé le conteneur musite ? Autrement, il est possible que ce soit l'ancienne image qui tourne encore. L'idéal serait de supprimer le conteneur, puis d'en re-créer un.

**Comment by jperon** [comment]
Quant au point d'exclamation de l'Ave Verum, c'est une erreur de syntaxe (dernière ligne, première syllabe, juste avant la parenthèse fermante). [Une fois corrigée](https://musite.dtdns.net/fr/Graduale/gabc/Sequence/AveVerum.gabc), ça marche.

**Comment by mimo38** [comment]
Effectivement, j'ai supprimé puis réinstallé l'image docker, et ça tourne comme il faut !
Problème résolu. Merci bien.
