### ISSUE TITLE
erreur Export Ly 

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#5]
Dans la version actuelle, la fonction d'exportation vers le format .ly engendre une "internal server error"
(exemple [ici](https://musite.dtdns.net/fr/_exporter/Completorium/gabc/Alleluia/Adorabo.gabc?fmt=ly))

Les dernières lignes du log donnent :

> KeyError: 'mode'
Traceback (most recent call last):
  File "/opt/musite/deps/bottle.py", line 937, in _handle
    return route.call(**args)
  File "/opt/musite/deps/bottle.py", line 1878, in wrapper
    rv = callback(*a, **ka)
  File "/opt/musite/deps/i18n.py", line 463, in wrapper
    return callback(*args, **kwargs)
  File "/opt/musite/serveur.py", line 70, in afficher
    contenu = fonction(*arguments, **parametres)
  File "/opt/musite/serveur.py", line 833, in document_exporter
    rq.query.fmt, rq.forms.decode()
  File "/opt/musite/deps/controleur.py", line 409, in exporter
    ).exporter(fmt)('tmp', f.motaleatoire(3))
  File "/opt/musite/deps/ext/gabc.py", line 249, in ly
    return self.gabc(fmt='ly', chemin=chemin, indice=indice)
  File "/opt/musite/deps/ext/gabc.py", line 240, in gabc
    self.preparer_gabc(fmt, fichier)
  File "/opt/musite/deps/ext/gabc.py", line 319, in preparer_gabc
    fichier.ecrire(str(dest))
  File "/opt/musite/deps/gabctk.py", line 1328, in ecrire
    fichier.ecrire(LILYPOND_ENTETE % {
AttributeError: 'str' object has no attribute 'ecrire'

**Comment by jperon** [comment]
Merci pour le signalement !
